[package]
name = "baselinux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
tracing = { version = "0.1", default-feature = false }
tracing-subscriber = "0.3"
